apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: brynjar2
  labels:
    app: brynjar2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: brynjar2
  template:
    metadata:
      labels:
        app: brynjar2
    spec:
      containers:
      - name: brynjar2
        image: registry.digitalocean.com/olsen/brynjar:latest
        ports:
          - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
