apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: brynjar2
  namespace: apps
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: "app.motoren.site"
    http:
      paths:
      - path: /brynjar
        pathType: Prefix
        backend:
          service:
            name: brynjar2
            port:
              number: 80