name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build-image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    -
      name: Login to GitLab
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com/olsen
        username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
        password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
      
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: user/Brynjar:latest
