name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
permissions:
  contents: read
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3

       - name: Log in to GitHub container registry
         uses: docker/login-action@v1.10.0
         with:
           registry: registry.digitalocean.com/olsen
           username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
           password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
           
       - name: Build latest
         run: docker build -t registry.digitalocean.com/olsen/brynjar:$(echo $GITHUB_SHA | head -c7) .
         
       - name: DigitalOcean Docker Image Publish
         uses: ripplr-io/docr-docker-publish@v1
         with:
          # Image path in the format registry-name/image-name
          image_path: registry.digitalocean.com/olsen/brynjar:$(echo $GITHUB_SHA | head -c7)


