name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
       - uses: actions/checkout@v3

       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1

       - name: Log in to GitHub container registry
         uses: docker/login-action@v1.10.0
         with:
           registry: registry.digitalocean.com/olsen
           username: ${{ secrets.DIGITAL_OCEAN_TOKEN }}
           password: ${{ secrets.DIGITAL_OCEAN_TOKEN }}

       - name: Build and push container image to registry
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: brynjar:latest
           file: ./Dockerfile
